### PR TITLE
Converts to TypeScript & adds unregister function

### PR DESCRIPTION
**Pull request by vkammerer**
Hello @danburzo ,

We have read [your article](https://dev.to/danburzo/pinch-me-i-m-zooming-gestures-in-the-dom-a0e) and are impressed with your work! It's obviously taken you a lot of time to work out all the various behaviours between browsers and OS, and the level of care and detail you went through to analyse what makes a good web gesture experience is remarkable.

So we have been using your code in our application and it is working well 👏

We would be happy to help you maintain it if you are interested?

However, we realise that we may have different requirements than what you intend for this repo. The biggest one is that we want to use TypeScript, for all the various advantages it brings. Is this something you are interested in? If yes, this PR brings a standard toolchain for using it, along with what would be needed to publish the package to npm.

If you think that TypeScript does not belong in this repo, and would rather keep JavaScript, we will maintain our own version and give you credit for your original implementation.

In this PR, your code was mostly just converted to TypeScript, but I've added two minor changes:
- `gesture` can either be an actual gesture, or hold the `null` value. It cannot be a boolean anymore as in your original implementation.
- the `okzoomer` function returns a function that will unregister event listeners. This enables SPA frameworks to call it when a component is unmounted.

Looking forward to reading your feedback!

### CODE REVIEW

**Comment by danburzo** [comment]
Hi Vincent,

Thank you for the kind words! I'm happy you found the article and code helpful. The latest version of the article sits on my computer waiting for the last edits, but life got in the way in the meantime :-). (Hopefully I'll be able to publish the final version some time in the near future).

The code in this repo is mostly supporting the article and in the final version it will be in a more didactic style, with copious comments, and only covering core functionality (with many adjacent concerns, such as unregistering the listeners, left as "exercises for the reader"). My intention is to provide a basis on which to develop code specific to each application, as the many knobs that can be tweaked are all over the internal functions, so I'm not seeing this as something that can necessarily be packaged and/or published to npm as-is.

For this small experiment TypeScript introduces too much additional complexity. Please feel free to reuse and build upon the code in any way you see fit (including publishing your version to npm), and let me know if the MIT license (under which I published by habit) is hindering in any way (which is not my intention). I'll also be happy to link to your implementation if you let me know where to find it!

**Comment by vkammerer** [comment]
Hi Dan,

Thank you for the reply, and good luck with your article's redaction. I look forward to reading your code's new version (`a more didactic style, with copious comments` sounds interesting).

So we will maintain our TS version separately and add functionalities like a returned unregister function, and also probably publish the package to npm. I don't have a link to share just now, but I will get back to you in this thread in the next days.

**Comment by vkammerer** [comment]
Hi Dan,

I finally found the time to publish our version:
- GH: https://github.com/skilitics/two-fingers
- NPM: https://www.npmjs.com/package/@skilitics/two-fingers

We give you credit for the original code, with links to both your article and your repo.

As you were saying, this is not as much a library as a collection of code snippets / experiments that an application could choose to implement in a custom way. However, it acts well as an isolated component for us, and I guess that other users could be happy with it too, which is why we published it to npm.

We had to come up with a name too, and `two-fingers` made the cut, even though the current implementation handles more that that (all "wheel" events are handled too...). What do you think?

**Comment by danburzo** [comment]
Looks very good! I'll link to the package in the final version of the article.

**Pull request closed without merging**
